添加测试分组发布

diff --git a/.github/workflows/module_controller_ci_build_batch_deploy_to_aliyun.yml b/.github/workflows/module_controller_ci_build_batch_deploy_to_aliyun.yml
--- a/.github/workflows/module_controller_ci_build_batch_deploy_to_aliyun.yml
+++ b/.github/workflows/module_controller_ci_build_batch_deploy_to_aliyun.yml
@@ -98,10 +98,6 @@ jobs:
         run: |
           kubectl get pod
 
-      - name: describe pod
-        run: |
-          kubectl describe pod
-
       - name: wait base pod available
         run: |
           kubectl wait --for=condition=available deployment/dynamic-stock-deployment --timeout=300s
@@ -110,6 +106,101 @@ jobs:
         run: |
           kubectl wait --for=condition=available deployment/module-controller --timeout=300s
 
-      - name: get pod
+      - name: apply moduledeployment batch release
         run: |
-          kubectl get pod
+          kubectl apply -f config/samples/ci/module-deployment_v1alpha1_moduledeployment_batch_provider.yaml
+
+      - name: get moduledeployment
+        run: |
+          kubectl get moduledeployment
+
+      - name: get modulereplicaset
+        run: |
+          kubectl get modulereplicaset
+
+      - run: sleep 15
+
+      - name: get module
+        run: |
+          kubectl get module -oyaml
+
+      - name: exist module
+        run: |
+          moduleCount=$(kubectl get module | wc -l)
+          if [[ $moduleCount -lt 1 ]]; then
+            echo "ERROR: 不存在module"
+            exit 1
+          fi
+
+      - name: wait module available
+        run: |
+          # 定义要等待的资源名称和字段值
+          modulename=$(kubectl get module -o name)
+          desired_field_value="Available"
+          
+          # 定义等待的超时时间（以秒为单位）
+          timeout_seconds=300
+          
+          start_time=$(date +%s)
+          end_time=$((start_time + timeout_seconds))
+          
+          while true; do
+            current_time=$(date +%s)
+            if [ $current_time -gt $end_time ]; then
+              echo "等待超时"
+              exit 1
+            fi
+          
+            # 使用 kubectl get 命令获取资源对象的详细信息，并提取自定义字段的值
+            field_value=$(kubectl get $modulename -o custom-columns=STATUS:.status.status --no-headers)
+          
+            if [ "$field_value" == "$desired_field_value" ]; then
+              echo "字段值已满足条件"
+              exit 0
+            else
+              echo "等待字段值满足条件..."
+              sleep 5  # 等待一段时间后再次检查
+            fi
+          done
+
+      - name: check moduledeployment pause
+        run: |
+          # 定义要等待的资源名称和字段值
+          moduledeploymentname=$(kubectl get moduledeployment -o name)
+          desired_field_value=true
+          
+          # 定义等待的超时时间（以秒为单位）
+          timeout_seconds=300
+          
+          start_time=$(date +%s)
+          end_time=$((start_time + timeout_seconds))
+          
+          while true; do
+            current_time=$(date +%s)
+            if [ $current_time -gt $end_time ]; then
+              echo "等待超时"
+              exit 1
+            fi
+          
+            # 使用 kubectl get 命令获取资源对象的详细信息，并提取自定义字段的值
+            field_value=$(kubectl get $moduledeploymentname -o custom-columns=PAUSE:.spec.pause --no-headers)
+          
+            if [ "$field_value" == "$desired_field_value" ]; then
+              echo "字段值已满足条件，执行分组确认"
+              kubectl patch $moduledeploymentname -p '{"spec":{"pause":false}}' --type=merge
+              exit 0
+            else
+              echo "等待字段值满足条件..."
+              sleep 5  # 等待一段时间后再次检查
+            fi
+          done
+
+      - run: sleep 15
+
+      - name: exist module
+        run: |
+          moduleCount=$(kubectl get module | wc -l)
+          if [[ $moduleCount -lt 2 ]]; then
+            echo "ERROR: 不存在module"
+            exit 1
+          fi
