原始ci添加扩容逻辑和直接删除pod逻辑

diff --git a/.github/workflows/module_controller_ci_build_deploy_to_aliyun.yml b/.github/workflows/module_controller_ci_build_deploy_to_aliyun.yml
--- a/.github/workflows/module_controller_ci_build_deploy_to_aliyun.yml
+++ b/.github/workflows/module_controller_ci_build_deploy_to_aliyun.yml
@@ -151,10 +151,6 @@ jobs:
 
       - run: sleep 15
 
-      - name: get module
-        run: |
-          kubectl get module -oyaml
-
       - name: not exist module
         run: |
           moduleCount=$(kubectl get module | wc -l)
@@ -162,3 +158,54 @@ jobs:
             echo "ERROR: module依旧存在"
             exit 1
           fi
+
+      - name: Apply moduledeployment scaleup module
+        run: |
+          kubectl apply -f config/samples/module-deployment_v1alpha1_moduledeployment_provider.yaml
+
+      - name: get moduledeployment
+        run: |
+          kubectl get moduledeployment
+
+      - name: get modulereplicaset
+        run: |
+          kubectl get modulereplicaset
+
+      - run: sleep 15
+
+      - name: get module
+        run: |
+          kubectl get module -oyaml
+
+      - name: exist module
+        run: |
+          moduleCount=$(kubectl get module | wc -l)
+          if [[ $moduleCount -lt 1 ]]; then
+            echo "ERROR: 不存在module"
+            exit 1
+          fi
+
+      - name: scaleup then check module
+        run: |
+          podname=$(kubectl get pod -l app=dynamic-stock -o name)
+          kubectl exec -it $podname -- sh -c 'ls -al'
+          kubectl exec -it $podname -- sh -c 'ls -al logs'
+          kubectl exec -it $podname -- sh -c 'ls -al logs/stock-mng'
+          kubectl exec -it $podname -- sh -c 'ls -al logs/stock-mng/sofa-ark'
+          kubectl exec -it $podname -- sh -c 'grep "dynamic-provider:1.0.0 started" logs/stock-mng/sofa-ark/*.log'
+
+      - name: delete pod
+        run: |
+          podname=$(kubectl get pod -l app=dynamic-stock -o name)
+          kubectl delete pod $podname
+
+      - run: sleep 30
+
+      - name: check module
+        run: |
+          podname=$(kubectl get pod -l app=dynamic-stock -o name)
+          kubectl exec -it $podname -- sh -c 'ls -al'
+          kubectl exec -it $podname -- sh -c 'ls -al logs'
+          kubectl exec -it $podname -- sh -c 'ls -al logs/stock-mng'
+          kubectl exec -it $podname -- sh -c 'ls -al logs/stock-mng/sofa-ark'
+          kubectl exec -it $podname -- sh -c 'grep "dynamic-provider:1.0.0 started" logs/stock-mng/sofa-ark/*.log'
