添加随机删除一个模块后等待模块安装

diff --git a/.github/workflows/module_controller_ci_build_batch_scaleup_then_scaledown_deploy_to_aliyun.yml b/.github/workflows/module_controller_ci_build_batch_scaleup_then_scaledown_deploy_to_aliyun.yml
--- a/.github/workflows/module_controller_ci_build_batch_scaleup_then_scaledown_deploy_to_aliyun.yml
+++ b/.github/workflows/module_controller_ci_build_batch_scaleup_then_scaledown_deploy_to_aliyun.yml
@@ -289,9 +289,143 @@ jobs:
             fi
           done
 
-      - name: random delete module
+      - name: random delete module then wait module available and delete base pod clean logs
         run: |
           resource_name=$(kubectl get module -o name | sort -R | head -n 1)
           base_instance_name=$(kubectl get $resource_name -o jsonpath='{.metadata.labels.serverless\.alipay\.com/base-instance-name}')
           echo "要删除的资源名称: $resource_name"
           echo "base-instance-name 的值: $base_instance_name"
+          kubectl delete $resource_name
+          
+          timeout_seconds=300
+          start_time=$(date +%s)
+          end_time=$((start_time + timeout_seconds))
+          
+          while true; do
+            moduleCount=$(kubectl get $resource_name | wc -l)
+            current_time=$(date +%s)
+            if [ $current_time -gt $end_time ]; then
+              echo "等待超时"
+            exit 1
+            fi
+          
+            if [[ $moduleCount -lt 1 ]]; then
+              echo "module已缩容"
+              exit 0
+            else
+              echo "等待module删除"
+              sleep 5
+            fi
+          done
+          
+          kubectl delete pod $base_instance_name
+          
+          timeout_seconds=300
+          start_time=$(date +%s)
+          end_time=$((start_time + timeout_seconds))
+          
+          while true; do
+            podcount=$(kubectl get pod $base_instance_name | wc -l)
+            current_time=$(date +%s)
+            if [ $current_time -gt $end_time ]; then
+              echo "等待超时"
+            exit 1
+            fi
+          
+            if [[ $podcount -lt 1 ]]; then
+              echo "pod已清理"
+              exit 0
+            else
+              echo "等待pod删除"
+              sleep 5
+            fi
+          done
+
+      - name: delete module then check exist module more then 1
+        run: |
+          moduleCount=$(kubectl get module | wc -l)
+          echo $moduleCount
+          if [[ $moduleCount -lt 2 ]]; then
+            echo "ERROR: 未达到指定module数量"
+            exit 1
+          fi
+
+      - name: get module
+        run: |
+          kubectl get module
+
+      - name: wait module available
+        run: |
+          # 定义要等待的资源类型和期望的字段值
+          moduletype="module"
+          desired_field_value="Available"
+          
+          # 定义等待的超时时间（以秒为单位）
+          timeout_seconds=300
+          
+          start_time=$(date +%s)
+          end_time=$((start_time + timeout_seconds))
+          
+          while true; do
+            current_time=$(date +%s)
+            if [ $current_time -gt $end_time ]; then
+              echo "等待超时"
+              exit 1
+            fi
+          
+            # 获取所有的资源对象名，并循环处理
+            for modulename in $(kubectl get $moduletype -o name); do
+              # 使用 kubectl get 命令获取每个资源对象的详细信息，并提取自定义字段的值
+              field_value=$(kubectl get $modulename -o custom-columns=STATUS:.status.status --no-headers)
+          
+              # 检查字段值是否满足期望
+              if [ "$field_value" != "$desired_field_value" ]; then
+                echo "等待字段值满足条件..."
+                sleep 5  # 等待一段时间后再次检查
+                continue 2  # 如果字段值未满足，则跳出循环，进入下一轮等待
+              fi
+            done
+          
+            # 如果所有资源对象的字段值都满足期望，则结束脚本
+            echo "字段值已满足条件"
+            exit 0
+          done
+
+      - name: delete module then check module install
+        run: |
+          label_selector="app=dynamic-stock"
+          max_attempts=10
+          timeout=300
+          interval=30
+          
+          for ((i=0; i<$max_attempts; i++)); do
+            echo "尝试 $((i+1))"
+            # 获取满足标签选择器条件的所有Pod
+            podnames=($(kubectl get pods -l $label_selector -o jsonpath='{.items[*].metadata.name}'))
+          
+            totalcount=0
+            # 遍历所有Pod进行日志检索
+            for podname in "${podnames[@]}"; do
+              log_entry=$(kubectl exec -it $podname -- sh -c 'grep "Install Biz: provider:1.0.2 success" ~/logs/sofa-ark/*.log || true' 2>/dev/null)
+              echo "totalcount：$totalcount"
+              if [ -n "$log_entry" ]; then
+                totalcount=$((totalcount + 1))
+              fi
+            done
+          
+            if [ $totalcount -eq 2 ]; then
+              echo "所有Pod都满足条件。"
+              exit 0
+            fi
+          
+            # 如果这不是最后一次尝试，则等待一段时间后继续
+            if [ $i -lt $((max_attempts-1)) ]; then
+              echo "有些Pod未满足条件。等待 $interval 秒后进行下一次尝试。"
+              sleep $interval
+            else
+              # 如果是最后一次尝试，则输出超时消息
+              echo "已达到最大尝试次数。有些Pod未满足条件。"
+              exit 1
+            fi
+          done
+          
